{\rtf1\ansi\ansicpg1252\cocoartf2638
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\froman\fcharset0 Times-Roman;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs26 \cf0 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 -
\fs24  
\fs26 hosts:
\fs24  
\fs26 redhat
\fs24 \
   
\fs26 remote_user:
\fs24  
\fs26 ansibleuser
\fs24 \
 #  
\fs26 vars_files:
\fs24 \
  #   
\fs26 -
\fs24  
\fs26 vars.yml
\fs24 \
   
\fs26 vars:
\fs24 \
     
\fs26 ansible_ssh_private_key_file:
\fs24  
\fs26 \'93~/.ssh/ANSIBLE\'94
\fs24 \
   
\fs26 tasks:
\fs24 \
     
\fs26 -
\fs24  
\fs26 name:
\fs24  
\fs26 Echo
\fs24  
\fs26 a
\fs24  
\fs26 hello
\fs24  
\fs26 message
\fs24 \
       
\fs26 command:
\fs24  
\fs26 echo
\fs24  
\fs26 hello
\fs24 \
}